import type { Metadata } from "next";
import { Atkinson_Hyperlegible } from "next/font/google";
import { GovUKFrontend } from "./components/govuk-frontend";
import "./globals.scss";
import ConfigureAmplifyClientSide from "./components/ConfigureAmplify";

const atkinson = Atkinson_Hyperlegible({
	weight: ["400", "700"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Hounslow Critical Service",
	description: "Generated by create next app",
};

export const viewport = {
	width: "device-width",
	initialScale: 1,
	viewportFit: "cover",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${atkinson.className} govuk-template`}>
			<head>
				<meta charSet="utf-8" />
				<meta name="theme-color" content="#0b0c0c" />
				<meta httpEquiv="X-UA-Compatible" content="IE=edge" />
			</head>
			<body className="govuk-template__body">
				<ConfigureAmplifyClientSide />
				<a
					href="#main-content"
					className="govuk-skip-link"
					data-module="govuk-skip-link"
				>
					Skip to main content
				</a>
				<header className="govuk-header" data-module="govuk-header">
					<div className="govuk-header__container govuk-width-container">
						<div className="govuk-header__content">
							<a
								href="/"
								className="govuk-header__link govuk-header__service-name"
							>
								Hounslow Critical Service
							</a>
						</div>
					</div>
				</header>
				<div className="govuk-width-container">
					<main className="govuk-main-wrapper" id="main-content">
						{children}
					</main>
				</div>
				<footer className="govuk-footer">
					<div className="govuk-width-container">
						<div className="govuk-footer__meta">
							<div className="govuk-footer__meta-item">
								© CRITICAL Channel 2025
							</div>
						</div>
					</div>
				</footer>
				<GovUKFrontend />
			</body>
		</html>
	);
}
