import type { Metadata } from "next";
import Script from "next/script";
import "./globals.scss";

export const metadata: Metadata = {
	title: "Your Service Name - GOV.UK",
	description: "Generated by create next app",
	viewport: "width=device-width, initial-scale=1, viewport-fit=cover",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="govuk-template">
			<body className="govuk-template__body">
				<Script id="govuk-frontend-init" strategy="beforeInteractive">
					{`document.body.className += ' js-enabled' + ('noModule' in HTMLScriptElement.prototype ? ' govuk-frontend-supported' : '')`}
				</Script>

				{children}

				<Script
					type="module"
					src="/node_modules/govuk-frontend/dist/govuk/govuk-frontend.min.js"
				/>
				<Script type="module" id="govuk-frontend-init-all">
					{`import { initAll } from '/node_modules/govuk-frontend/dist/govuk/govuk-frontend.min.js'
						initAll()`}
				</Script>
			</body>
		</html>
	);
}
