import type { Metadata } from "next";
import { Atkinson_Hyperlegible } from "next/font/google";
import { GovUKFrontend } from "./components/govuk-frontend";
import "./globals.scss";

const atkinson = Atkinson_Hyperlegible({
	weight: ["400", "700"],
	subsets: ["latin"],
	display: "swap",
});

export const metadata: Metadata = {
	title: "Hounslow Critical Service",
	description: "Generated by create next app",
};

export const viewport = {
	width: "device-width",
	initialScale: 1,
	viewportFit: "cover",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${atkinson.className} govuk-template`}>
			<head>
				<meta charSet="utf-8" />
				<meta name="theme-color" content="#0b0c0c" />
				<meta httpEquiv="X-UA-Compatible" content="IE=edge" />
			</head>
			<body className="govuk-template__body">
				{children}
				<GovUKFrontend />
			</body>
		</html>
	);
}
